<a href="https://colab.research.google.com/github/martinmaturana777/AED-Apuntes/blob/main/PautaAuxiliar1_2025_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Pauta Auxiliar 1

**Auxiliares: Valentina Alarcón Yañez, Antonia G. Calvo, Cristián Llull, Raimundo Lorca Correa, Samuel Chavéz Fierro<br>
Profesores: Nelson Baloian, Iván Sipirán, Patricio Poblete<br>
Curso: CC3001 Algoritmos y Estructuras de Datos**

---
## Preliminar: ¿Qué es un invariante?

El invariante es una afirmación lógica, es decir, se puede verificar si es verdadero o falso.

Condiciones que debe cumplir un invariante para que esté bien definido:

* Debe ser verificable y verdadero en todo momento, es decir, antes de empezar un ciclo, luego de cada iteración realizada y tras finalizar el ciclo.
  > **Obs:** es posible que el invariante se rompa (su valor de verdad sea falso) **durante** una iteración, sin embargo, debe volver a cumplirse antes de terminar la iteración.

* Debe estar en función de TODOS sus índices/iteradores/contadores.

* Debe tener una condición inicial y una condición de término acorde.

Se llama invariante porque a pesar de estar definido en función de elementos variables (Ej: `for i in range(0,20)`), la afirmación es siempre la misma, es decir, no depende del valor que tome el iterador/contador.



---
## **P1. Bandera Holandesa**

###a) Analice los posibles invariantes del problema y dibújelos


En este caso es bastante más complejo poder intuír cuales serán los invariantes que nos permitan resolver el problema. La idea general para afrontar este problema es poder mantener una estructura que sea nuestro invariante.
<br>


Como pueden observar en la imagen de abajo, nuestra situación inicial es Q, donde tenemos un arreglo con los elementos desordenados y R es al arreglo al cual debemos llegar.

Los arreglos con letras rojas representan 4 posibles invariantes que se pueden usar para resolver el problema.




![](https://drive.google.com/uc?export=view&id=1ZcAwxJekswfwj8he6_HkFVHMcdMbugw0)


Estas 4 estructuras funcionan como invariantes del problema, pues en todo momento podremos identificar un grupo que sea rojo, un grupo blanco, un grupo azul y un grupo indeterminado. La idea será partir con los grupos de colores vacíos y a medida que vamos recorriendo la lista podremos ir colocando valores en los grupos rojo, blanco y azul, según corresponda. Eventualmente lograremos clasificar todos los colores y el grupo indeterminado quedará vacío.

Notemos que lo único que cambia en nuestros 4 modelos de invariantes son el orden en el que ponemos el grupo indeterminado, que para efectos de resolver el problema cualquiera de los 4 invariantes funcionarían.


### b) Programe la solución al problema siguiendo alguno de los invariantes de la parte __a)__:

El invariante que usaremos será el de la esquina inferior izquierda. La idea del algoritmo es mantener 3 contadores, los cuales delimitan los trozos del arreglo en que estamos agrupando los colores.

Usaremos algunos indices para representar el invariante del dibujo:

* Desde el indice __0__ hasta el indice __i__ (sin incluirlo) estarán los elementos de color rojo

* Desde el indice __i__ hasta el indice __j__ (sin incluirlo) estarán los elementos de color blanco

* Desde el indice __j__ hasta el indice __k__ estarán los elementos que aun no sabemos de que color son y no hemos acomodado aún.

* Desde el indice __k__ (sin incluirlo) hasta el indice __n-1__ (donde __n__ es el total de elementos) estarán los elementos de color azul

Por lo tanto, la idea del algoritmo es ir avanzando el indice __j__ e ir acomodando los elementos que vayamos viendo. Para acomodarlos correctamente debemos manejar los indices __i__ y __k__ correctamente. Es importante notar que el elemento al que apunta __i__ no es rojo, ya que apunta al siguiente espacio donde puede ir un elemento rojo. Esto nos permite hacer un rápido intercambio de elementos. Lo mismo ocurre para los otros indices.

En el momento que el indice __j__ supere al indice __k__ ya estaran vistos todos los elementos y por tanto ya se encuentran ordenados.

Para simplificar el código usaremos el número 0 para representar el color rojo, el número 1 para respresentar el color blanco y el número 2 para el color azul

In [ ]:
def ordenarBandera(arr):
  i = 0                     #i,j,k serán los índices que nos permiten definir nuestro invariante
  j = 0
  k = len(arr)-1            #k parte siendo el último elemento de la lista porque su recorrido es de atrás hacía adelante
  while(j <= k):            #condición de término
    if arr[j]==0:           #caso en el que encontramos el color rojo
      arr[i], arr[j] = arr[j], arr[i]    #intercambiamos los valores del índice i y del índice j
      i += 1                #como el color rojo aumento en 1 ahora debemos avanzar un valor el indice
      j += 1                #aumentamos el valor de j para analizar el siguiente elemento de la lista
    elif arr[j]==1:         #caso en el que encontramos el color blanco
      j += 1                #aumentamos el valor de j para analizar el siguiente elemento de la lista
    else:                   #caso en el que encontramos el color azul
      arr[j], arr[k] = arr[k], arr[j]     #intercambiamos los valores del índice j y del índice k
      k -= 1                              #como el color azul aumento en 1 ahora debemos retroceder un valor el indice k
         #OJO! no es necesario aumentar en 1 el valor de j, pues el índice k almacenaba un valor desconocido.
  return arr           #retornamos el mismo arreglo que recibimos, pero en este caso ya está modificado según lo pedido


In [ ]:
#Veamos un ejemplo:

arr = np.array([0, 1, 1, 0, 1, 2, 1, 2, 0, 0, 0, 1])
ordenados = ordenarBandera(arr)
print(ordenados)

[0 0 0 0 0 1 1 1 1 1 2 2]


---
## **P2. Partición de Lomuto y Hoare**

El ordenamiento rápido (_quicksort_ en ingles), es un algoritmo creado por el científico británico en computación C.A.R.Hoare. La magia de este algoritmo está en el uso de la función partición, la cual dado un arreglo y un elemento dentro del arreglo llamado pivote, realiza las siguientes tareas:
 1. Seleccionar un pivote (puede elegirse cualquiera, existen distintas técnicas).
 2. Situar el pivote en la posición que ocupará dentro del arreglo si este estuviese ordenado.
 3. Sitúa todos los elementos menores o iguales que el pivote a la izquierda, y todos los elementos mayores que el pivote a la derecha de este.

Existen varios algoritmos para realizar la partición de un arreglo, unos de lo más conocidos son **la partición de Hoare y la partición de Lomuto.** Para las explicaciones que siguen asumiremos el primer elemento del arreglo como pivote.

 **Partición de Hoare**: Si partimos con el arreglo `4,5,3,1,2`, este variará de la siguiente forma:
  `4,5,3,1,2` ->
  `4,5,3,1,2` ->
  `2,4,3,1,5` ->
  `2,3,4,1,5` ->
  `2,3,1,4,5`

**Partición de Lomuto**: Si partimos con el arreglo `4,5,3,1,2`, este variará de la siguiente forma:
`4,5,3,1,2` ->
`4,5,3,1,2` ->
`4,5,3,1,2` ->
`3,4,5,1,2` ->
`3,1,4,5,2` ->`3,1,2,4,5`
(a) Implemente el algoritmo de la partición de Hoare con una función:
``` particionHoare(x, ini, fin, pos_pivote)```

(b) Implemente el algoritmo de la particion de Lomuto con una función:
``` particionLomuto(x, ini, fin, pos_pivote)```

(c) Especifique cuál es el invariante del ciclo en cada caso.

Donde ``` x``` es el arreglo de NumPy a particionar, los parámetros ``` ini``` y ``` fin``` son enteros que representan la posición inicial y final del arreglo que se quiere particionar, y 'pivote' es el índice del mismo .

Primero explicaremos la idea tras la partición de Hoare.

- Toma dos punteros, los cuales llamaremos i y j, los cuales comienzan en el principio y final del arreglo respectivamente.
- Junto con esto también selecciona un pivote, el cual se puede encontrar en cualquier lugar del arreglo.
- Para comenzar, el pivote se coloca en el inicio del arreglo y se avanza i.
- Luego, el puntero i comienza a avanzar siempre y cuando los elementos sean menores al pivote, si encuentra uno que es mayor se detiene en ese elemento.
- Seguido de esto, el puntero j comienza un procedimiento análogo desde el lado derecho, para los mayores al pivote.
- Cuando i está apuntando a un elemento mayor y j a uno menor, se debe hacer un swap para corregir el invariante. El elemento al que apunta i se pasa al lugar del elemento apuntado por j y el apuntado por j se pasa al lugar del elemento apuntado por i (se hace un swap de los elementos).
- Luego, se hace swap de i con el pivote, para dejar el pivote siempre a la derecha de los menores.
- Se vuelve a realizar el movimiento ya descrito de los punteros y el swap de elementos hasta que i sea mayor a j.

In [ ]:
# Código Hoare
def hoare(arreglo, ini, fin, pos_pivote):
  # 1: variables iniciales
  i = ini
  j = fin
  pivote = arreglo[pos_pivote]

  # 2: mover pivote a "mayor de los menores"
  arreglo[pos_pivote], arreglo[i] = arreglo[i], arreglo[pos_pivote]
  pos_pivote = i
  i = i + 1

  # 3: iterar sobre el arreglo
  while True:
    if i > j:
      break
    elif arreglo[i] <= pivote:
      arreglo[i], arreglo[pos_pivote] = arreglo[pos_pivote], arreglo[i]
      pos_pivote = i
      i += 1
    elif arreglo[j] > pivote:
      j -= 1
    else:
      arreglo[i], arreglo[j] = arreglo[j], arreglo[i] #hacer swap de a[i] con a[j]
      arreglo[i], arreglo[pos_pivote] = arreglo[pos_pivote], arreglo[i]
      pos_pivote = i
      i += 1
      j -= 1
  return arreglo, pos_pivote

In [ ]:
# Test hoare
def test_hoare(a, pos_pivote):
  print("Arreglo inicial")
  print(a)
  print("Pivote: {}".format(a[pos_pivote]))
  print("Arreglo pivoteado:")
  print(hoare(a, 0, len(a)-1, pos_pivote))
  hoa, m = hoare(a, 0, len(a)-1, pos_pivote)
  print(hoa)
  p = hoa[m]
  print()
  print("Partición OK" if (m==0 or max(a[0:m])<=p) and (m==len(a) or min(a[m:])>=p)
          else "Error")
  print()

a = np.arange(10)
np.random.shuffle(a)
pos_pivote = 0
test_hoare(a, pos_pivote)

arrays = [
    np.array([4, 0, 7, 3, 2, 1, 8, 5, 9, 6]),
    np.array([1, 5, 9, 4, 7, 2, 0, 3, 8, 6]),
    np.array([8, 1, 0, 5, 4, 7, 6, 3, 9, 2]),
    np.array([9, 5, 3, 4, 6, 2, 0, 7, 8, 1]),
    np.array([1, 2, 0]),
    np.array([8, 1, 0, 5, 4, 7, 6, 3, 9, 2])
]
pivotes = [
    0,
    0,
    0,
    0,
    1,
    5
]

for array, pivote in zip(arrays, pivotes):
  test_hoare(array, pivote)


Arreglo inicial
[2 8 1 7 0 9 6 5 4 3]
Pivote: 2
Arreglo pivoteado:
(array([0, 1, 2, 7, 8, 9, 6, 5, 4, 3]), 2)
[0 1 2 7 8 9 6 5 4 3]

Partición OK

Arreglo inicial
[4 0 7 3 2 1 8 5 9 6]
Pivote: 4
Arreglo pivoteado:
(array([0, 1, 3, 2, 4, 7, 8, 5, 9, 6]), 4)
[0 1 3 2 4 7 8 5 9 6]

Partición OK

Arreglo inicial
[1 5 9 4 7 2 0 3 8 6]
Pivote: 1
Arreglo pivoteado:
(array([0, 1, 9, 4, 7, 2, 5, 3, 8, 6]), 1)
[0 1 9 4 7 2 5 3 8 6]

Partición OK

Arreglo inicial
[8 1 0 5 4 7 6 3 9 2]
Pivote: 8
Arreglo pivoteado:
(array([1, 0, 5, 4, 7, 6, 3, 2, 8, 9]), 8)
[0 1 5 4 7 6 3 2 8 9]

Partición OK

Arreglo inicial
[9 5 3 4 6 2 0 7 8 1]
Pivote: 9
Arreglo pivoteado:
(array([5, 3, 4, 6, 2, 0, 7, 8, 1, 9]), 9)
[3 4 1 2 0 5 7 8 6 9]

Partición OK

Arreglo inicial
[1 2 0]
Pivote: 2
Arreglo pivoteado:
(array([1, 0, 2]), 2)
[0 1 2]

Partición OK

Arreglo inicial
[8 1 0 5 4 7 6 3 9 2]
Pivote: 7
Arreglo pivoteado:
(array([1, 0, 5, 4, 2, 6, 3, 7, 9, 8]), 7)
[0 5 4 2 1 3 6 7 9 8]

Partición OK



- La idea de esta partición es mantener dos punteros, pero esta vez ambos comienzan apuntando al principio del arreglo.
- Luego, se comienza a mover el índice j, en cada movimiento del índice vamos a revisar si el elemento es menor al pivote, si es que esto es así, aumentamos en uno el valor de i y realizamos un swap entre el elemento al cual esta apuntando i con el que apunta j.
- Después, un swap de i con el pivote para mantener el invariante.
- En caso de que esto no se cumpla, simplemente avanza el índice j sin que que se realice ninguna acción.
- De esta forma, se va cumpliendo que todos los elementos a la izquierda de i son menores al pivote y los que están entre i y j son mayores al pivote.
- Cuando el índice j llega al final del arreglo, se hace un swap de la posición i+1 con el pivote.

In [ ]:
# Código Lomuto
def lomuto(arreglo, ini, fin, pos_pivote):
  # 1: Inicializar variables
  j = ini
  i = ini
  pivote = arreglo[pos_pivote]

  # 2: mover pivote a mayor de los menores
  arreglo[i], arreglo[pos_pivote] = arreglo[pos_pivote], arreglo[i]
  pos_pivote = i
  i += 1
  j += 1

  # 3: Iterar sobre arreglo
  while j <= fin:
    print(i, j)
    if arreglo[j] > pivote:
      j += 1
    elif arreglo[j] <= pivote:
      # Swap
      arreglo[i], arreglo[j] = arreglo[j], arreglo[i]
      # Swap con pivote
      arreglo[i], arreglo[pos_pivote] = arreglo[pos_pivote], arreglo[i]
      pos_pivote = i
      i += 1
      j += 1

  return arreglo, pos_pivote

In [ ]:
#Test Lomuto
def test_lomuto(a, pos_pivote):
  print("Arreglo inicial")
  print(a)
  print("Pivote: {}".format(a[pos_pivote]))
  print("Arreglo pivoteado:")
  lom, m = lomuto(a, 0, len(a)-1, pos_pivote)
  print(lom)
  p = lom[m]
  print()
  print("Partición OK" if (m==0 or max(a[0:m])<=p) and (m==len(a) or min(a[m:])>=p)
          else "Error")
  print()

a = np.arange(10)
np.random.shuffle(a)
pos_pivote = 0
test_lomuto(a, pos_pivote)

arrays = [
    np.array([4, 9, 3, 8, 5, 6, 7, 2, 0, 1]),
    np.array([2, 0, 1]),
    np.array([2, 9, 0, 1, 1]),
    np.array([4, 0, 7, 3, 2, 1, 8, 5, 9, 6]),
    np.array([1, 5, 9, 4, 7, 2, 0, 3, 8, 6]),
    np.array([8, 1, 0, 5, 4, 7, 6, 3, 9, 2]),
    np.array([9, 5, 3, 4, 6, 2, 0, 7, 8, 1]),
    np.array([1, 2, 0]),
    np.array([8, 1, 0, 5, 4, 7, 6, 3, 9, 2])
]
pivotes = [
    0,
    2,
    3,
    0,
    0,
    0,
    0,
    1,
    5
]

for array, pivote in zip(arrays, pivotes):
  test_lomuto(array, pivote)

Arreglo inicial
[3 6 4 9 7 2 1 0 5 8]
Pivote: 3
Arreglo pivoteado:
1 1
1 2
1 3
1 4
1 5
2 6
3 7
4 8
4 9
[2 1 0 3 7 6 4 9 5 8]

Partición OK

Arreglo inicial
[4 9 3 8 5 6 7 2 0 1]
Pivote: 4
Arreglo pivoteado:
1 1
1 2
2 3
2 4
2 5
2 6
2 7
3 8
4 9
[3 2 0 1 4 6 7 9 8 5]

Partición OK

Arreglo inicial
[2 0 1]
Pivote: 1
Arreglo pivoteado:
1 1
2 2
[0 1 2]

Partición OK

Arreglo inicial
[2 9 0 1 1]
Pivote: 1
Arreglo pivoteado:
1 1
1 2
2 3
2 4
[0 1 1 2 9]

Partición OK

Arreglo inicial
[4 0 7 3 2 1 8 5 9 6]
Pivote: 4
Arreglo pivoteado:
1 1
2 2
2 3
3 4
4 5
5 6
5 7
5 8
5 9
[0 3 2 1 4 7 8 5 9 6]

Partición OK

Arreglo inicial
[1 5 9 4 7 2 0 3 8 6]
Pivote: 1
Arreglo pivoteado:
1 1
1 2
1 3
1 4
1 5
1 6
2 7
2 8
2 9
[0 1 9 4 7 2 5 3 8 6]

Partición OK

Arreglo inicial
[8 1 0 5 4 7 6 3 9 2]
Pivote: 8
Arreglo pivoteado:
1 1
2 2
3 3
4 4
5 5
6 6
7 7
8 8
8 9
[1 0 5 4 7 6 3 2 8 9]

Partición OK

Arreglo inicial
[9 5 3 4 6 2 0 7 8 1]
Pivote: 9
Arreglo pivoteado:
1 1
2 2
3 3
4 4
5 5
6 6
7 7
8 8
9 9
[5 3 4 6 2 0 

---
## **P3. Suma Objetivo (Propuesto)**

Dado un arreglo ordenado ascendente con $n$ números enteros diferentes y un entero $T$, se pide encontrar dos números cuya suma sea exactamente $T$ y retornar sus índices. En caso de que esta tupla no exista, se debería retornar $(-1, -1)$.

Para esto construya una función: ``` sumaObjetivo(arr, T)```

*Solución* :

Podemos entender este problema como una busqueda dentro del arreglo. Entonces mientras existan elementos en el arreglo, quedan pares de números por revisar. Por lo que podemos plantear la idea que hasta el momento ningún par comparado ha dado como suma T. Esto nos permitirá establecer el invariante.


**Invariante**
* Mientras $i < j$, no hay ningún par compuesto de un elemento de $A[0..i-1]$ y un elemento de $A[j-1...n-1]$ que su suma sea T.

**Condiciones Iniciales**

* $i = 0$
* $j = n - 1$

**Condición de termino**

* $i > j$ dado que no quedan elementos por comparar.
* $i = j$ se llegó a un mismo elemento, por lo cual no existen pares de números.




In [ ]:
def sumaobjetivo(arr, T):
  i = 0;
  j = len(arr)-1
  while i < j:
     suma = arr[i] + arr[j]
     if suma == T:
        return i, j
     elif suma < T:
        i +=1
     elif suma > T:
        j -=1
  return -1, -1

In [ ]:
a = np.array([-69, 0, 7 , 9, 42, 70, 90, 271, 314,400])

print(sumaobjetivo(a,1))
print(sumaobjetivo(a,97))
print(sumaobjetivo(a,84))

(0, 5)
(2, 6)
(-1, -1)
